version: "3"
services:
  hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:latest
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  cucumber-tests-chrome:
    image: entireframeworkimage:latest
    depends_on:
      - hub
    environment:
      - browser=Chrome
    volumes:
       - ./htmlReportsChrome:/home/SeleniumCucumberTestFramework/test-output

  cucumber-tests-Firefox:
    image: seleniumjenkinsdockerimage:latest
    depends_on:
      - hub
    environment:
      - browser=Firefox
    volumes:
       - ./htmlReportsFirefox:/home/SeleniumCucumberTestFramework/test-output

      
